language: node_js

node_js:
  - '10'

install:
  - npm install -g vuepress

script:
  - vuepress build

cache:
  directories:
    - 'node_modules'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target-branch: master
  on:
    branch: master
